# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-15 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('item_name', models.CharField(max_length=1024)),
                ('item_description', models.TextField(blank=True, null=True)),
                ('listing_id', models.CharField(max_length=255)),
                ('seller_sku', models.CharField(max_length=255)),
                ('price', models.FloatField(default=0.0)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('open_date', models.CharField(max_length=30)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('item_is_marketplace', models.CharField(max_length=2)),
                ('product_id_type', models.CharField(max_length=10)),
                ('zshop_shipping_fee', models.FloatField(blank=True, null=True)),
                ('item_note', models.TextField(blank=True, null=True)),
                ('item_condition', models.CharField(blank=True, max_length=255, null=True)),
                ('zshop_category1', models.CharField(blank=True, max_length=255, null=True)),
                ('zshop_browse_path', models.CharField(blank=True, max_length=255, null=True)),
                ('zshop_storefront_feature', models.CharField(blank=True, max_length=255, null=True)),
                ('asin1', models.CharField(max_length=255)),
                ('asin2', models.CharField(blank=True, max_length=255, null=True)),
                ('asin3', models.CharField(blank=True, max_length=255, null=True)),
                ('will_ship_internationally', models.CharField(blank=True, max_length=255, null=True)),
                ('expedited_shipping', models.CharField(blank=True, max_length=255, null=True)),
                ('zshop_boldface', models.CharField(blank=True, max_length=255, null=True)),
                ('product_id', models.CharField(max_length=255)),
                ('bid_for_featured_placement', models.CharField(blank=True, max_length=255, null=True)),
                ('add_delete', models.CharField(blank=True, max_length=255, null=True)),
                ('pending_quantity', models.IntegerField(blank=True, null=True)),
                ('fulfillment_channel', models.CharField(max_length=255)),
                ('merchant_shipping_group', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
