# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-15 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.TextField(),
        ),
    ]
