# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-15 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0002_auto_20170515_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_is_marketplace',
            field=models.CharField(max_length=10),
        ),
    ]
