# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-15 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0003_auto_20170515_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_is_marketplace',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='product_id_type',
            field=models.CharField(max_length=255),
        ),
    ]
