# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-16 06:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0004_auto_20170515_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('author', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('comment_count', models.IntegerField(default=0)),
                ('post_date', models.DateField()),
                ('rating', models.FloatField(default=5.0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon.Item')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
