# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-16 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0005_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
