# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-17 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0006_auto_20170516_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='send_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='asin1',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
