# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-22 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0007_auto_20170517_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='top_critical_review_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
