# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-19 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0008_item_top_critical_review_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailPageSalesTraffic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('dt', models.DateField(db_index=True)),
                ('parent_asin', models.CharField(max_length=255)),
                ('child_asin', models.CharField(db_index=True, max_length=255)),
                ('title', models.TextField()),
                ('sku', models.CharField(max_length=255)),
                ('sessions', models.PositiveIntegerField()),
                ('session_percentage', models.FloatField()),
                ('page_views', models.PositiveIntegerField()),
                ('page_views_percentage', models.FloatField()),
                ('buy_box_percentage', models.FloatField()),
                ('units_ordered', models.PositiveIntegerField()),
                ('unit_session_percentage', models.FloatField()),
                ('ordered_product_sales', models.FloatField()),
                ('currency', models.CharField(max_length=10)),
                ('total_order_items', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
