# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-20 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0010_cookie'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='avg_unit_session_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
