# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-16 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0012_remove_detailpagesalestraffic_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('AmazonOrderId', models.CharField(db_index=True, max_length=255)),
                ('PurchaseDate', models.DateTimeField()),
                ('OrderStatus', models.CharField(max_length=255)),
                ('MarketplaceId', models.CharField(max_length=255)),
                ('BuyerEmail', models.EmailField(max_length=255)),
                ('BuyerName', models.CharField(max_length=255)),
                ('OrderType', models.CharField(max_length=255)),
                ('PurchaseOrderNumber', models.CharField(max_length=255)),
                ('data', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
