# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-17 02:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0013_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cookie',
        ),
        migrations.RemoveField(
            model_name='order',
            name='PurchaseOrderNumber',
        ),
    ]
