# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-17 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0014_auto_20171017_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='BuyerEmail',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='BuyerName',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
