# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-24 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0015_auto_20171017_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.TextField(blank=True, null=True),
        ),
    ]
